chore: set modbus-serial version to "8.0.17"
modbus-serial@8.0.19 causes issues

Error: node_modules/modbus-serial/ServerSerial.d.ts(5,37): error TS7016: Could not find a declaration file for module './servers/serverserial_pipe_handler'. '/Users/runner/work/node-wot/node-wot/node_modules/modbus-serial/servers/serverserial_pipe_handler.js' implicitly has an 'any' type.

see https://github.com/yaacov/node-modbus-serial/issues/581