chore: increase dev version to 0.8.4
Note: limited vm2 dependency to "3.9.11" since latest version "3.9.12" causes build issues

node_modules/vm2/index.d.ts:38:40 - error TS1176: Interface declaration cannot have 'implements' clause.

38 export interface VMFileSystemInterface implements VMFS, VMPath {
                                          ~~~~~~~~~~

node_modules/vm2/index.d.ts:46:14 - error TS2420: Class 'VMFileSystem' incorrectly implements interface 'VMFileSystemInterface'.
  Property 'isSeparator' is missing in type 'VMFileSystem' but required in type 'VMFileSystemInterface'.

46 export class VMFileSystem implements VMFileSystemInterface {
                ~~~~~~~~~~~~

  node_modules/vm2/index.d.ts:40:2
    40  isSeparator(char: string): boolean;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'isSeparator' is declared here.