fix: latest modbus-serial-8.0.7 seems to cause issues
node_modules/modbus-serial/ModbusRTU.d.ts:2:22 - error TS7016: Could not find a declaration file for module './ports/testport'. 'C:/Projects/WoT/thingweb/thingweb.node-wot-danielpeintner/node_modules/modbus-serial/ports/testport.js' implicitly has an 'any' type.

2 import TestPort from './ports/testport';